config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # get "tasks", to: "tasks#all"

  # post "tasks", to: "tasks#create"
  # get "tasks/new", to: "tasks#new"

  # get "tasks/:id/edit", to: "tasks#edit", as: :edit
  # patch "tasks/:id", to: "tasks#update"

  # get "tasks/:id", to: "tasks#show", as: :task

  # delete "tasks/:id", to: "tasks#destroy"

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @aya = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body class="p-3">
  <div class="w-50">
    <%= yield %>
  </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: aya do |f| %>
  <%= f.label :title, :class => "font-weight-bold" %>
  <%= f.text_field :title, :class => "form-control my-2" %>
  <%= f.label :details, :class => "font-weight-bold"  %>
  <%= f.text_area :details, :class => "form-control my-2" %>
  <% if !aya.new_record? %>
    <div>
      <%= f.check_box :completed %>
      <%= f.label :completed, "Completed" %>
    </div>
  <% end %>
  <%= f.submit 'Update Task', :class => "btn btn-primary my-2" %>
<% end %>

app/views/tasks/all.html.erb
<h1>My Tasks</h1>
<% @tasks.each do |task| %>
  <p>
    <% if task.completed %>
      <i class="fa-regular fa-circle-check"></i>
    <% else %>
      <i class="fa-regular fa-circle"></i>
    <% end %>
    <%= link_to task.title, task_path(task), class: "text-decoration-none" %>
    <%= link_to task_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
  </p>
<% end %>

<hr>

<p>
  <i class="fa-solid fa-plus"></i>
  <%= link_to "Add a new task", tasks_new_path, class: "text-decoration-none" %>
</p>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render 'form', aya: @task %>

<hr>

<p>
  <i class="fa-solid fa-arrow-rotate-left"></i>
  <%= link_to "Back to list", tasks_path %>
</p>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<% @tasks.each do |task| %>
  <p>
    <% if task.completed %>
      <i class="fa-regular fa-circle-check"></i>
    <% else %>
      <i class="fa-regular fa-circle"></i>
    <% end %>
    <%= link_to task.title, task_path(task), class: "text-decoration-none" %>
    <%= link_to task_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
  </p>
<% end %>

<hr>

<p>
  <i class="fa-solid fa-plus"></i>
  <%= link_to "Add a new task", new_task_path, class: "text-decoration-none" %>
</p>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form', aya: @aya %>

<hr>

<p>
  <i class="fa-solid fa-arrow-rotate-left"></i>
  <%= link_to "Back to list", tasks_path %>
</p>

app/views/tasks/show.html.erb
<div class="d-flex justify-content-between align-items-start">
  <h1><%= @task.title %></h1>
  <%= link_to edit_task_path(@task), class: "text-decoration-none text-reset" do %>
    <button class="btn btn-light mb-2">
      <i class="fa-solid fa-pen-to-square"></i>
      Edit this task
    </button>
  <% end %>
</div>

<p class="border rounded bg-light p-2"><%= @task.details %></p>

<p>
  <% if @task.completed %>
    <i class="fa-regular fa-circle-check"></i>
    This task is completed
  <% else %>
    <i class="fa-regular fa-circle"></i>
    This task is not completed yet
  <% end %>
</p>

<hr>

<p>
  <i class="fa-solid fa-arrow-rotate-left"></i>
  <%= link_to "Back to list", tasks_path %>
</p>